### ISSUE TITLE
CALL and RUN verb

### ISSUE THREAD

**Issue by StephanWald** [BBx-Kitchen/bbj-language-server#52]
```
CALL "bus.bbj::setUpdateLocation", mapRC%, mapUser$, mapPassword$, mapVendor$, mapApplication$, mapVersion$, mapLevel%, mapLocation
```

```
RUN "TEST"
```

**Comment by dhuebner** [comment]
`CALL fileid{::label}{,ERR=lineref}{,expr...}`
`RUN {fileid{,ERR=lineref}}`

Syntactically not very challenging, but it depends on additional features like validation and maybe jump to file or the label in `CALL`

**Comment by insafuhrmann** [comment]
First step: should not produce errors. Further support can be implemented later if necessary.

**Comment by insafuhrmann** [comment]
First step is resolved.

**Comment by insafuhrmann** [comment]
@StephanWald Should we close this issue and open a new one when follow up tasks are needed (validation, jumping etc.)?

**Comment by StephanWald** [comment]
1st step resolved. We'll open detailed issues on potentially still missing aspects.
